spring:
  application:
    name: microservice-product-server

server:
  port: 32001

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---
spring:
  profiles:
    docker
  application:
    name: microservice-product-server

server:
  port: 32001

eureka:
  instance:
    hostname: sc-eureka-server
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/